import os
import logging
import httpx
from typing import Dict, Any, List, Tuple
from dotenv import load_dotenv
from .ollama import generate_grounded_answer

load_dotenv()

logger = logging.getLogger("raglens.llm")

# Input validation limits to protect free-tier quotas and memory
MAX_QUESTION_LENGTH = 1000
MAX_CONTEXT_LENGTH = 12000

GROQ_ENDPOINT = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL = "llama-3.3-70b-versatile"

def validate_and_format_input(question: str, context_chunks: List[Dict[str, Any]]) -> Tuple[str, str]:
    """
    Validates and truncates input question and document context to prevent resource abuse.
    """
    clean_question = question.strip()
    if len(clean_question) > MAX_QUESTION_LENGTH:
        clean_question = clean_question[:MAX_QUESTION_LENGTH] + "... [truncated]"

    formatted_context_list = []
    total_len = 0
    for c in context_chunks:
        chunk_str = f"[Source Chunk #{c.get('chunk_index', 0)} - {c.get('document_filename', 'Doc')}]:\n{c.get('content', '')}"
        if total_len + len(chunk_str) > MAX_CONTEXT_LENGTH:
            remaining = MAX_CONTEXT_LENGTH - total_len
            if remaining > 50:
                formatted_context_list.append(chunk_str[:remaining] + "... [truncated]")
            break
        formatted_context_list.append(chunk_str)
        total_len += len(chunk_str)

    context_text = "\n\n".join(formatted_context_list)
    return clean_question, context_text

def get_llm_response(question: str, context_chunks: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Main LLM dispatcher function.
    Switches between 'ollama' and 'groq' based on the LLM_PROVIDER environment variable.
    """
    provider = os.getenv("LLM_PROVIDER", "ollama").strip().lower()

    if provider == "groq":
        return _call_groq_llm(question, context_chunks)
    else:
        return generate_grounded_answer(question=question, context_chunks=context_chunks)

def _call_groq_llm(question: str, context_chunks: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Calls Groq API via OpenAI-compatible endpoint using model llama-3.3-70b-versatile.
    Safely handles errors without leaking API keys, raw error bodies, or stack traces.
    """
    api_key = os.getenv("GROQ_API_KEY", "").strip()
    if not api_key or api_key == "paste_your_real_key_here":
        logger.warning("Groq provider selected, but GROQ_API_KEY is not configured or uses default placeholder.")
        return {
            "ai_answer": "AI service temporarily unavailable",
            "ollama_connected": False,
            "grounded": False,
            "provider": "groq"
        }

    clean_question, context_text = validate_and_format_input(question, context_chunks)

    system_prompt = (
        "You are answering a question using the provided document context.\n"
        "Use only the supplied context.\n"
        "If the answer cannot be determined from the context, say that there is not enough information in the provided document.\n"
        "Do not invent facts."
    )

    user_prompt = (
        f"DOCUMENT CONTEXT:\n{context_text}\n\n"
        f"QUESTION: {clean_question}\n\n"
        f"ANSWER:"
    )

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": GROQ_MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        "temperature": 0.2
    }

    try:
        with httpx.Client(timeout=60.0) as client:
            resp = client.post(GROQ_ENDPOINT, headers=headers, json=payload)
            if resp.status_code == 200:
                data = resp.json()
                choices = data.get("choices", [])
                if choices and len(choices) > 0:
                    answer = choices[0].get("message", {}).get("content", "").strip()
                    if not answer:
                        answer = "No response generated by AI service."
                    return {
                        "ai_answer": answer,
                        "ollama_connected": True,
                        "grounded": True,
                        "provider": "groq"
                    }

            # Log HTTP failure code internally without exposing API key or response text to client
            logger.error("Groq API call returned HTTP status code %s", resp.status_code)
            return {
                "ai_answer": "AI service temporarily unavailable",
                "ollama_connected": False,
                "grounded": False,
                "provider": "groq"
            }
    except Exception as e:
        # Catch network timeouts, rate limits, connection errors securely
        logger.error("Groq API call failed due to an exception.")
        return {
            "ai_answer": "AI service temporarily unavailable",
            "ollama_connected": False,
            "grounded": False,
            "provider": "groq"
        }
