import os
import httpx
from typing import Dict, Any, List
from dotenv import load_dotenv

load_dotenv()

OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434").rstrip("/")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama3.2:3b")

def check_ollama_status() -> Dict[str, Any]:
    """
    Check if local Ollama service is reachable and list available models.
    """
    url = f"{OLLAMA_BASE_URL}/api/tags"
    try:
        with httpx.Client(timeout=3.0) as client:
            resp = client.get(url)
            if resp.status_code == 200:
                data = resp.json()
                models = [m.get("name") for m in data.get("models", [])]
                is_configured_model_available = any(
                    OLLAMA_MODEL in m or m.startswith(OLLAMA_MODEL.split(":")[0])
                    for m in models
                )
                return {
                    "connected": True,
                    "url": OLLAMA_BASE_URL,
                    "model": OLLAMA_MODEL,
                    "available_models": models,
                    "message": f"Connected to Ollama. Model '{OLLAMA_MODEL}' is ready." if is_configured_model_available else f"Ollama connected. Note: Configured model '{OLLAMA_MODEL}' may need 'ollama pull {OLLAMA_MODEL}'."
                }
    except Exception as e:
        pass
        
    return {
        "connected": False,
        "url": OLLAMA_BASE_URL,
        "model": OLLAMA_MODEL,
        "available_models": [],
        "message": f"Ollama is not running at {OLLAMA_BASE_URL}. Start Ollama locally to enable AI answer generation."
    }

def generate_grounded_answer(question: str, context_chunks: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Send prompt with retrieved context to Ollama local LLM.
    """
    status = check_ollama_status()
    if not status["connected"]:
        return {
            "ai_answer": "Ollama is not running. Start Ollama to generate an AI answer.",
            "ollama_connected": False,
            "grounded": True
        }

    # Format context for prompt
    context_text = "\n\n".join([
        f"[Source Chunk #{c['chunk_index']} - {c['document_filename']}]:\n{c['content']}"
        for c in context_chunks
    ])

    system_prompt = (
        "You are answering a question using the provided document context.\n"
        "Use only the supplied context.\n"
        "If the answer cannot be determined from the context, say that there is not enough information in the provided document.\n"
        "Do not invent facts."
    )

    user_prompt = (
        f"DOCUMENT CONTEXT:\n{context_text}\n\n"
        f"QUESTION: {question}\n\n"
        f"ANSWER:"
    )

    full_prompt = f"{system_prompt}\n\n{user_prompt}"

    try:
        url = f"{OLLAMA_BASE_URL}/api/generate"
        payload = {
            "model": OLLAMA_MODEL,
            "prompt": full_prompt,
            "stream": False,
            "options": {
                "temperature": 0.2
            }
        }
        with httpx.Client(timeout=60.0) as client:
            response = client.post(url, json=payload)
            if response.status_code == 200:
                result = response.json()
                answer = result.get("response", "").strip()
                if not answer:
                    answer = "No response generated by local LLM."
                return {
                    "ai_answer": answer,
                    "ollama_connected": True,
                    "grounded": True
                }
            else:
                return {
                    "ai_answer": f"Ollama returned HTTP {response.status_code}: {response.text}",
                    "ollama_connected": True,
                    "grounded": False
                }
    except Exception as e:
        return {
            "ai_answer": f"Could not connect to Ollama model endpoint: {str(e)}",
            "ollama_connected": False,
            "grounded": False
        }
